language: go

go:
  - 1.7.x

sudo: required

services:
  - docker

before_install:
  - go get github.com/golang/lint/golint

script:
  # Generally build out everything we need.
  - cd ratchet
  - golint
  - go test -v
  - go build
  - cd ../
  - cd ratchet-child
  - golint
  - go test -v
  - go build
  # Next steps, run it with the CNI docker stuff?