apiVersion: v1
kind: Pod
metadata:
  name: testrouter
  labels:
    app: testrouter
    ratchet: "true"
spec:
  containers:
    - name: testrouter
      image: dougbtv/centos-network
      command: ["/bin/bash"]
      args: ["-c", "while true; do sleep 10; done"]